packages:
  - .

allowBuilds:
  '@firebase/util': true
  protobufjs: true
  sharp: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
  - protobufjs

overrides:
  import-in-the-middle: "1.11.2"
